// Generated by CoffeeScript 1.6.3
(function() {
  var person, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.AppView = (function(_super) {
    __extends(AppView, _super);

    function AppView() {
      _ref = AppView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    AppView.prototype.tagName = "li";

    AppView.prototype.template = _.template("<%= name %> (<%= school %>)");

    AppView.prototype.className = 'person';

    AppView.prototype.id = 'personId';

    AppView.prototype.initialize = function() {
      return this.render();
    };

    AppView.prototype.render = function() {
      return this.template(this.model.toJSON());
    };

    return AppView;

  })(Backbone.View);

  person = new App.Models.Person();

  window.perView = new AppView({
    model: person
  });

}).call(this);

/*
//@ sourceMappingURL=AppView.map
*/
