// Generated by CoffeeScript 1.7.1
(function() {
  describe("deck constructor", function() {
    return it("should create a card collection", function() {
      var collection;
      collection = new Deck();
      return expect(collection.length).toBe(52);
    });
  });

}).call(this);

//# sourceMappingURL=CardSpec.map
