// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  (function() {
    var addNodeView, checkKey, collectionNodes, nodeCollectionView, vent;
    window.App = {
      Models: {},
      Collections: {},
      Views: {}
    };
    window.selectedNode = {
      model: null,
      offsetX: 0,
      offsetY: 0
    };
    window.Transform = {
      deltaX: 0,
      deltaY: 0,
      zoom: 1.0,
      centerX: 0,
      centerY: 0
    };
    vent = _.extend({}, Backbone.Events);
    window.template = function(id) {
      return _.template($("#" + id).html());
    };
    $(document.body).mousemove(function(event) {
      var selectedNode;
      event.preventDefault();
      if (window.selectedNode.model) {
        selectedNode = window.selectedNode.model;
        selectedNode.set({
          top: event.pageY - window.selectedNode.offsetY
        });
        return selectedNode.set({
          left: event.pageX - window.selectedNode.offsetX
        });
      }
    });
    $(document.body).on("mouseup", function(event) {
      return window.selectedNode.model = null;
    });
    checkKey = function(e) {
      e || e.preventDefault();
      e = e || window.event;
      console.log("Event is: " + e.keyCode);
      if (e.keyCode === 38) {
        window.Transform.deltaY += 10 * window.Transform.zoom;
        vent.trigger('translate');
        return console.log("up arrow " + window.Transform.deltaY);
      } else if (e.keyCode === 40) {
        window.Transform.deltaY -= 10 * window.Transform.zoom;
        vent.trigger('translate');
        return console.log("down arrow " + window.Transform.deltaY);
      } else if (e.keyCode === 37) {
        window.Transform.deltaX += 10 * window.Transform.zoom;
        vent.trigger('translate');
        return console.log("left arrow " + window.Transform.deltaX);
      } else if (e.keyCode === 39) {
        window.Transform.deltaX -= 10 * window.Transform.zoom;
        vent.trigger('translate');
        return console.log("right arrow " + window.Transform.deltaX);
      } else if (e.keyCode === 73) {
        window.Transform.centerX = $('body').width() / 2;
        window.Transform.centerY = $('body').height() / 2;
        window.Transform.zoom *= 1.5;
        vent.trigger('zoom');
        return console.log(window.Transform.zoom);
      } else if (e.keyCode === 79) {
        window.Transform.centerX = $('body').width() / 2;
        window.Transform.centerY = $('body').height() / 2;
        window.Transform.zoom *= 0.67;
        vent.trigger('zoom');
        return console.log(window.Transform.zoom);
      }
    };
    document.onkeydown = checkKey;
    App.Models.Node = (function(_super) {
      __extends(Node, _super);

      function Node() {
        return Node.__super__.constructor.apply(this, arguments);
      }

      Node.prototype.defaults = {
        username: "Mikey Testing T",
        text: 'Hack Reactor',
        top: null,
        left: null
      };

      Node.prototype.validate = function(attrs) {
        if (attrs.text === null) {
          return "Text requires a valid string";
        }
      };

      return Node;

    })(Backbone.Model);
    App.Views.Node = (function(_super) {
      __extends(Node, _super);

      function Node() {
        return Node.__super__.constructor.apply(this, arguments);
      }

      Node.prototype.tagName = 'li';

      Node.prototype.template = template('nodeTemplate');

      Node.prototype.initialize = function() {
        this.model.on('change', this.update, this);
        this.model.on('destroy', this.remove, this);
        vent.on('translate', this.translate, this);
        return vent.on('zoom', this.zoom, this);
      };

      Node.prototype.events = {
        'click .edit': 'editNode',
        'click .delete': 'deleteNode',
        'mousedown span': 'mouseDownSelectNode',
        'mouseenter': 'mouseenter',
        'mouseleave': 'mouseleave'
      };

      Node.prototype.mouseenter = function() {
        return this.$el.find('.nodeMenu').css('visibility', 'visible');
      };

      Node.prototype.mouseleave = function() {
        return this.$el.find('.nodeMenu').css('visibility', 'hidden');
      };

      Node.prototype.mouseDownSelectNode = function(e) {
        var nodePositionX, nodePositionY, offsetX, offsetY;
        e.preventDefault();
        nodePositionX = parseInt(this.$el.css('left')) || this.$el.position().left;
        nodePositionY = parseInt(this.$el.css('top')) || this.$el.position().top;
        offsetX = event.pageX - nodePositionX;
        offsetY = event.pageY - nodePositionY;
        return window.selectedNode = {
          model: this.model,
          offsetX: parseInt(offsetX),
          offsetY: parseInt(offsetY)
        };
      };

      Node.prototype.editNode = function() {
        var currentNode, newText;
        newText = prompt("Edit the text:", this.model.get('text'));
        if (newText === null) {
          return;
        }
        currentNode = this.model;
        return currentNode.set({
          'text': newText
        });
      };

      Node.prototype.deleteNode = function() {
        return this.model.collection.remove(this.model);
      };

      Node.prototype.remove = function() {
        return this.$el.remove();
      };

      Node.prototype.zoom = function() {
        var distFromCenterX, distFromCenterY, transX, transY, x, y, zoom;
        x = this.model.get("left") + this.$el.width() / 2 + window.Transform.deltaX;
        y = this.model.get('top') + this.$el.height() / 2 + window.Transform.deltaY;
        zoom = window.Transform.zoom;
        distFromCenterX = x - window.Transform.centerX;
        distFromCenterY = y - window.Transform.centerY;
        transX = window.Transform.centerX + (x - window.Transform.centerX) * zoom;
        transY = window.Transform.centerY + (y - window.Transform.centerY) * zoom;
        this.$el.css({
          'transform': "scale(" + zoom + ")"
        });
        this.$el.css({
          'left': transX - this.$el.width() / 2
        });
        return this.$el.css({
          'top': transY - this.$el.height() / 2
        });
      };

      Node.prototype.translate = function() {
        var distFromCenterX, distFromCenterY, transX, transY, x, y, zoom;
        x = this.model.get("left") + this.$el.width() / 2 + window.Transform.deltaX;
        y = this.model.get('top') + this.$el.height() / 2 + window.Transform.deltaY;
        zoom = window.Transform.zoom;
        distFromCenterX = x - window.Transform.centerX;
        distFromCenterY = y - window.Transform.centerY;
        transX = window.Transform.centerX + (x - window.Transform.centerX) * zoom;
        transY = window.Transform.centerY + (y - window.Transform.centerY) * zoom;
        this.$el.css({
          'transform': "scale(" + zoom + ")"
        });
        this.$el.css({
          'left': transX - this.$el.width() / 2
        });
        return this.$el.css({
          'top': transY - this.$el.height() / 2
        });
      };

      Node.prototype.translate2 = function() {
        var deltaX, deltaY, position, x, y, zoom;
        x = this.model.get("left");
        y = this.model.get('top');
        zoom = window.Transform.zoom;
        deltaX = window.Transform.deltaX;
        deltaY = window.Transform.deltaY;
        position = {
          left: (x + deltaX) * zoom + "px",
          top: (y + deltaY) * zoom + "px"
        };
        this.$el.css('position', 'absolute');
        this.$el.css(position);
        return this;
      };

      Node.prototype.update = function() {
        var template, x, y;
        if ((this.model.changedAttributes().text)) {
          template = this.template(this.model.toJSON());
          return this.$el.html(template);
        } else {
          x = this.model.get("left");
          y = this.model.get('top');
          this.$el.css('left', x);
          this.$el.css('top', y);
          return this;
        }
      };

      Node.prototype.render = function() {
        var template, x, y;
        template = this.template(this.model.toJSON());
        this.$el.html(template);
        this.$el.css('position', 'absolute');
        x = this.model.get("left");
        y = this.model.get('top');
        this.$el.css('left', x);
        this.$el.css('top', y);
        return this;
      };

      return Node;

    })(Backbone.View);
    App.Collections.Nodes = (function(_super) {
      __extends(Nodes, _super);

      function Nodes() {
        return Nodes.__super__.constructor.apply(this, arguments);
      }

      Nodes.prototype.model = App.Models.Node;

      Nodes.prototype.firebase = new Firebase('https://resplendent-fire-9007.firebaseio.com/');

      return Nodes;

    })(Backbone.Firebase.Collection);
    App.Views.NodesCollection = (function(_super) {
      __extends(NodesCollection, _super);

      function NodesCollection() {
        return NodesCollection.__super__.constructor.apply(this, arguments);
      }

      NodesCollection.prototype.tagName = 'div';

      NodesCollection.prototype.initialize = function() {
        this.collection.on('add', this.addOne, this);
        return this.collection.on('remove', this.removeOne, this);
      };

      NodesCollection.prototype.rerender = function() {
        return this.collection.each(function(node) {
          return node.render();
        }, this);
      };

      NodesCollection.prototype.render = function() {
        this.collection.each(this.addOne, this);
        return this;
      };

      NodesCollection.prototype.addOne = function(node) {
        var nodeView;
        nodeView = new App.Views.Node({
          model: node
        });
        nodeView.$el.attr("id", node.id);
        return this.$el.prepend(nodeView.render().el);
      };

      NodesCollection.prototype.removeOne = function(model, coll, opt) {
        return $("#" + model.id).detach();
      };

      return NodesCollection;

    })(Backbone.View);
    App.Views.AddNode = (function(_super) {
      __extends(AddNode, _super);

      function AddNode() {
        return AddNode.__super__.constructor.apply(this, arguments);
      }

      AddNode.prototype.el = '#addNote';

      AddNode.prototype.events = {
        'submit': 'submit'
      };

      AddNode.prototype.submit = function(e) {
        var node, text, username;
        e.preventDefault();
        text = $(e.currentTarget).find('input[name=text]').val();
        username = $(e.currentTarget).find('input[name=username]').val();
        node = new App.Models.Node({
          text: text || "empty",
          username: username || 'anonymous'
        });
        return this.collection.add(node);
      };

      return AddNode;

    })(Backbone.View);
    collectionNodes = new App.Collections.Nodes();
    addNodeView = new App.Views.AddNode({
      collection: collectionNodes
    });
    nodeCollectionView = new App.Views.NodesCollection({
      collection: collectionNodes
    });
    return $(".nodes").append(nodeCollectionView.render().el);
  })();

}).call(this);

//# sourceMappingURL=App.map
